sudo: required

language: node_js

os:
  - osx
  - linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - python3-pip
    - python3.5
    - g++-7

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CC=gcc-7; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-7; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig; fi
  - openssl version
  - ./travis-before-install
  - openssl version

node_js:
  - 8

install:
  - npm install --verbose

script:
  - npm test

notifications:
  email: false